# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: guruguru.proto for package ''

require 'grpc'
require 'guruguru_pb'

module BossService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'BossService'

    rpc :Join, JoinRequest, JoinResponse
  end

  Stub = Service.rpc_stub_class
end
module MemberService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'MemberService'

    rpc :Poke, PokeRequest, PokeResponse
    rpc :SetNext, SetNextRequest, SetNextResponse
  end

  Stub = Service.rpc_stub_class
end
