// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guruguru.proto

/*
Package guruguru is a generated protocol buffer package.

It is generated from these files:
	guruguru.proto

It has these top-level messages:
	Member
	Res
	JoinRequest
	PokeRequest
	SetNextRequest
*/
package guruguru

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	HostPort string `protobuf:"bytes,2,opt,name=host_port,json=hostPort" json:"host_port,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

type Res struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Res) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type JoinRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type PokeRequest struct {
	From    *Member `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PokeRequest) Reset()                    { *m = PokeRequest{} }
func (m *PokeRequest) String() string            { return proto.CompactTextString(m) }
func (*PokeRequest) ProtoMessage()               {}
func (*PokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PokeRequest) GetFrom() *Member {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *PokeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetNextRequest struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
}

func (m *SetNextRequest) Reset()                    { *m = SetNextRequest{} }
func (m *SetNextRequest) String() string            { return proto.CompactTextString(m) }
func (*SetNextRequest) ProtoMessage()               {}
func (*SetNextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetNextRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func init() {
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*Res)(nil), "Res")
	proto.RegisterType((*JoinRequest)(nil), "JoinRequest")
	proto.RegisterType((*PokeRequest)(nil), "PokeRequest")
	proto.RegisterType((*SetNextRequest)(nil), "SetNextRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BossService service

type BossServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Res, error)
}

type bossServiceClient struct {
	cc *grpc.ClientConn
}

func NewBossServiceClient(cc *grpc.ClientConn) BossServiceClient {
	return &bossServiceClient{cc}
}

func (c *bossServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/BossService/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BossService service

type BossServiceServer interface {
	Join(context.Context, *JoinRequest) (*Res, error)
}

func RegisterBossServiceServer(s *grpc.Server, srv BossServiceServer) {
	s.RegisterService(&_BossService_serviceDesc, srv)
}

func _BossService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BossServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BossService/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BossServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BossService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BossService",
	HandlerType: (*BossServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _BossService_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guruguru.proto",
}

// Client API for MemberService service

type MemberServiceClient interface {
	Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*Res, error)
	SetNext(ctx context.Context, in *SetNextRequest, opts ...grpc.CallOption) (*Res, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/MemberService/Poke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) SetNext(ctx context.Context, in *SetNextRequest, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/MemberService/SetNext", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberService service

type MemberServiceServer interface {
	Poke(context.Context, *PokeRequest) (*Res, error)
	SetNext(context.Context, *SetNextRequest) (*Res, error)
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_Poke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Poke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Poke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Poke(ctx, req.(*PokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_SetNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).SetNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/SetNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).SetNext(ctx, req.(*SetNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poke",
			Handler:    _MemberService_Poke_Handler,
		},
		{
			MethodName: "SetNext",
			Handler:    _MemberService_SetNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guruguru.proto",
}

func init() { proto.RegisterFile("guruguru.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x69, 0x0c, 0x49, 0x3b, 0xa9, 0x11, 0x06, 0x84, 0xd0, 0x1e, 0x2c, 0x7b, 0xd2, 0xcb,
	0x82, 0xf1, 0xe4, 0x55, 0x3c, 0x09, 0x95, 0xb2, 0x7d, 0x00, 0x69, 0x65, 0xac, 0x25, 0x6c, 0xa7,
	0xee, 0x6c, 0xc4, 0xc7, 0x97, 0xec, 0xa6, 0x10, 0x3d, 0xf5, 0xb0, 0xb0, 0xfb, 0xef, 0x37, 0xfc,
	0x1f, 0x03, 0xe5, 0xae, 0x75, 0x6d, 0x77, 0xf4, 0xd1, 0xb1, 0x67, 0xf5, 0x08, 0xd9, 0x92, 0xec,
	0x96, 0x1c, 0x22, 0xa4, 0x87, 0x8d, 0xa5, 0x6a, 0xb4, 0x18, 0xdd, 0x4e, 0x4c, 0xb8, 0xe3, 0x1c,
	0x26, 0x9f, 0x2c, 0xfe, 0xed, 0xc8, 0xce, 0x57, 0x49, 0xf8, 0x18, 0x77, 0xc1, 0x8a, 0x9d, 0x57,
	0xd7, 0x70, 0x61, 0x48, 0xb0, 0x84, 0x84, 0x9b, 0x30, 0x35, 0x36, 0x09, 0x37, 0x4a, 0x43, 0xf1,
	0xc2, 0xfb, 0x83, 0xa1, 0xaf, 0x96, 0xc4, 0xe3, 0x0d, 0x64, 0x36, 0x14, 0x04, 0xa4, 0xa8, 0x73,
	0x1d, 0xfb, 0x4c, 0x1f, 0xab, 0x67, 0x28, 0x56, 0xdc, 0xd0, 0x89, 0x9f, 0x43, 0xfa, 0xe1, 0xd8,
	0xfe, 0xa7, 0x43, 0x88, 0x15, 0xe4, 0x96, 0x44, 0x36, 0x3b, 0xea, 0x6d, 0x4e, 0x4f, 0x75, 0x0f,
	0xe5, 0x9a, 0xfc, 0x2b, 0xfd, 0xf8, 0x73, 0x8b, 0xeb, 0x3b, 0x28, 0x9e, 0x58, 0x64, 0x4d, 0xee,
	0x7b, 0xff, 0x4e, 0x38, 0x83, 0xb4, 0xf3, 0xc6, 0xa9, 0x1e, 0xe8, 0xcf, 0x52, 0x6d, 0x48, 0xea,
	0x25, 0x5c, 0xc6, 0xe1, 0x01, 0xdc, 0x49, 0xe3, 0x54, 0x0f, 0xdc, 0x23, 0x8c, 0x0b, 0xc8, 0x7b,
	0x15, 0xbc, 0xd2, 0x7f, 0xa5, 0x22, 0xb1, 0xcd, 0xc2, 0xee, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x93, 0x26, 0x2a, 0x4e, 0x8d, 0x01, 0x00, 0x00,
}
