version: '3.5'
services:
  boss:
    build: ./boss
    volumes:
      - "./boss:/go/src/github.com/hakobe/grpc-guruguru/boss"
    environment:
      HOST_PORT: 0.0.0.0:5000
    command: go run boss.go
  go:
    build: ./go
    volumes:
      - "./go:/go/src/github.com/hakobe/grpc-guruguru/go"
    depends_on:
      - boss
    environment:
      MEMBER_NAME: go
      HOST_PORT: 0.0.0.0:5000
      PUBLIC_HOST_PORT: go:5000
      BOSS_HOST_PORT: boss:5000
    command: go run member.go
  python:
    build: ./python
    volumes:
      - "./python:/app"
    depends_on:
      - boss
    environment:
      MEMBER_NAME: python
      HOST_PORT: 0.0.0.0:5000
      PUBLIC_HOST_PORT: python:5000
      BOSS_HOST_PORT: boss:5000
  node:
    build: ./node
    volumes:
      - "./node:/app"
    depends_on:
      - boss
    environment:
      MEMBER_NAME: node
      HOST_PORT: 0.0.0.0:5000
      PUBLIC_HOST_PORT: node:5000
      BOSS_HOST_PORT: boss:5000
