// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guruguru.proto

/*
Package guruguru is a generated protocol buffer package.

It is generated from these files:
	guruguru.proto

It has these top-level messages:
	Member
	JoinRequest
	JoinResponse
	PokeRequest
	PokeResponse
	SetNextRequest
	SetNextResponse
*/
package guruguru

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	HostPort string `protobuf:"bytes,2,opt,name=host_port,json=hostPort" json:"host_port,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

type JoinRequest struct {
	JoiningMember *Member `protobuf:"bytes,1,opt,name=joining_member,json=joiningMember" json:"joining_member,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JoinRequest) GetJoiningMember() *Member {
	if m != nil {
		return m.JoiningMember
	}
	return nil
}

type JoinResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type PokeRequest struct {
	FromMember *Member `protobuf:"bytes,1,opt,name=from_member,json=fromMember" json:"from_member,omitempty"`
	Message    string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PokeRequest) Reset()                    { *m = PokeRequest{} }
func (m *PokeRequest) String() string            { return proto.CompactTextString(m) }
func (*PokeRequest) ProtoMessage()               {}
func (*PokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PokeRequest) GetFromMember() *Member {
	if m != nil {
		return m.FromMember
	}
	return nil
}

func (m *PokeRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PokeResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *PokeResponse) Reset()                    { *m = PokeResponse{} }
func (m *PokeResponse) String() string            { return proto.CompactTextString(m) }
func (*PokeResponse) ProtoMessage()               {}
func (*PokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PokeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SetNextRequest struct {
	NextMember *Member `protobuf:"bytes,1,opt,name=next_member,json=nextMember" json:"next_member,omitempty"`
}

func (m *SetNextRequest) Reset()                    { *m = SetNextRequest{} }
func (m *SetNextRequest) String() string            { return proto.CompactTextString(m) }
func (*SetNextRequest) ProtoMessage()               {}
func (*SetNextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetNextRequest) GetNextMember() *Member {
	if m != nil {
		return m.NextMember
	}
	return nil
}

type SetNextResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *SetNextResponse) Reset()                    { *m = SetNextResponse{} }
func (m *SetNextResponse) String() string            { return proto.CompactTextString(m) }
func (*SetNextResponse) ProtoMessage()               {}
func (*SetNextResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SetNextResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Member)(nil), "Member")
	proto.RegisterType((*JoinRequest)(nil), "JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "JoinResponse")
	proto.RegisterType((*PokeRequest)(nil), "PokeRequest")
	proto.RegisterType((*PokeResponse)(nil), "PokeResponse")
	proto.RegisterType((*SetNextRequest)(nil), "SetNextRequest")
	proto.RegisterType((*SetNextResponse)(nil), "SetNextResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BossService service

type BossServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
}

type bossServiceClient struct {
	cc *grpc.ClientConn
}

func NewBossServiceClient(cc *grpc.ClientConn) BossServiceClient {
	return &bossServiceClient{cc}
}

func (c *bossServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/BossService/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BossService service

type BossServiceServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
}

func RegisterBossServiceServer(s *grpc.Server, srv BossServiceServer) {
	s.RegisterService(&_BossService_serviceDesc, srv)
}

func _BossService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BossServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BossService/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BossServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BossService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BossService",
	HandlerType: (*BossServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _BossService_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guruguru.proto",
}

// Client API for MemberService service

type MemberServiceClient interface {
	Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error)
	SetNext(ctx context.Context, in *SetNextRequest, opts ...grpc.CallOption) (*SetNextResponse, error)
}

type memberServiceClient struct {
	cc *grpc.ClientConn
}

func NewMemberServiceClient(cc *grpc.ClientConn) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) Poke(ctx context.Context, in *PokeRequest, opts ...grpc.CallOption) (*PokeResponse, error) {
	out := new(PokeResponse)
	err := grpc.Invoke(ctx, "/MemberService/Poke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) SetNext(ctx context.Context, in *SetNextRequest, opts ...grpc.CallOption) (*SetNextResponse, error) {
	out := new(SetNextResponse)
	err := grpc.Invoke(ctx, "/MemberService/SetNext", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberService service

type MemberServiceServer interface {
	Poke(context.Context, *PokeRequest) (*PokeResponse, error)
	SetNext(context.Context, *SetNextRequest) (*SetNextResponse, error)
}

func RegisterMemberServiceServer(s *grpc.Server, srv MemberServiceServer) {
	s.RegisterService(&_MemberService_serviceDesc, srv)
}

func _MemberService_Poke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).Poke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/Poke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).Poke(ctx, req.(*PokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_SetNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).SetNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MemberService/SetNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).SetNext(ctx, req.(*SetNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poke",
			Handler:    _MemberService_Poke_Handler,
		},
		{
			MethodName: "SetNext",
			Handler:    _MemberService_SetNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guruguru.proto",
}

func init() { proto.RegisterFile("guruguru.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xa4, 0xa5, 0x34, 0xed, 0xcb, 0x47, 0x65, 0x4f, 0x21, 0x82, 0x68, 0xbc, 0xf4, 0x20, 0x7b,
	0x88, 0x27, 0x05, 0x2f, 0x1e, 0x05, 0xa5, 0xa6, 0x3f, 0xa0, 0x34, 0xf2, 0x8c, 0x31, 0x64, 0x5f,
	0xdc, 0xdd, 0x48, 0x7f, 0xbe, 0xec, 0x26, 0x95, 0xad, 0x98, 0xc3, 0xc2, 0xbe, 0x1d, 0x66, 0xe6,
	0xcd, 0xb0, 0x10, 0x95, 0x9d, 0xec, 0xcc, 0xe1, 0xad, 0x24, 0x4d, 0xe9, 0x1d, 0xcc, 0x9f, 0xb1,
	0x29, 0x50, 0x32, 0x06, 0x33, 0xb1, 0x6f, 0x30, 0x9e, 0x5c, 0x4e, 0xd6, 0xcb, 0xdc, 0xde, 0xd9,
	0x39, 0x2c, 0x3f, 0x48, 0xe9, 0x5d, 0x4b, 0x52, 0xc7, 0x53, 0x0b, 0x2c, 0xcc, 0xc3, 0x86, 0xa4,
	0x4e, 0x1f, 0xc0, 0x7f, 0xa2, 0x4a, 0xe4, 0xf8, 0xd5, 0xa1, 0xd2, 0x8c, 0x43, 0xf4, 0x49, 0x95,
	0xa8, 0x44, 0xb9, 0x6b, 0xac, 0xa2, 0x55, 0xf2, 0x33, 0x8f, 0xf7, 0x06, 0x79, 0x38, 0xc0, 0xfd,
	0x98, 0x5e, 0x40, 0xd0, 0xd3, 0x55, 0x4b, 0x42, 0x21, 0x8b, 0x60, 0x4a, 0xb5, 0xe5, 0x2c, 0xf2,
	0x29, 0xd5, 0xe9, 0x2b, 0xf8, 0x1b, 0xaa, 0xf1, 0x28, 0xbf, 0x06, 0xff, 0x5d, 0x52, 0x33, 0xa2,
	0x0d, 0x06, 0x1b, 0x82, 0xc4, 0xe0, 0x35, 0xa8, 0xd4, 0xbe, 0xc4, 0x61, 0xe5, 0xe3, 0x68, 0x2c,
	0x7b, 0xc9, 0x11, 0xcb, 0x7b, 0x88, 0xb6, 0xa8, 0x5f, 0xf0, 0xa0, 0x1d, 0x57, 0x81, 0x07, 0x3d,
	0xe6, 0x6a, 0xb0, 0x21, 0xce, 0x15, 0xac, 0x7e, 0xb9, 0xff, 0xcb, 0x67, 0x19, 0xf8, 0x8f, 0xa4,
	0xd4, 0x16, 0xe5, 0x77, 0xf5, 0x86, 0xec, 0x1a, 0x66, 0xa6, 0x00, 0x16, 0x70, 0xa7, 0xc6, 0x24,
	0xe4, 0x6e, 0x2b, 0x59, 0x01, 0x61, 0x6f, 0xe0, 0xb0, 0x4c, 0x06, 0x16, 0x70, 0xa7, 0x9d, 0x24,
	0xe4, 0x27, 0xc1, 0x6e, 0xc0, 0x1b, 0x96, 0x61, 0x2b, 0x7e, 0x1a, 0x29, 0x39, 0xe3, 0x7f, 0xf6,
	0x2c, 0xe6, 0xf6, 0x2b, 0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x42, 0xc4, 0x3d, 0x82, 0x1c,
	0x02, 0x00, 0x00,
}
