# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import guruguru_pb2 as guruguru__pb2


class BossServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Join = channel.unary_unary(
        '/BossService/Join',
        request_serializer=guruguru__pb2.JoinRequest.SerializeToString,
        response_deserializer=guruguru__pb2.JoinResponse.FromString,
        )


class BossServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Join(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BossServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Join': grpc.unary_unary_rpc_method_handler(
          servicer.Join,
          request_deserializer=guruguru__pb2.JoinRequest.FromString,
          response_serializer=guruguru__pb2.JoinResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BossService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MemberServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Poke = channel.unary_unary(
        '/MemberService/Poke',
        request_serializer=guruguru__pb2.PokeRequest.SerializeToString,
        response_deserializer=guruguru__pb2.PokeResponse.FromString,
        )
    self.SetNext = channel.unary_unary(
        '/MemberService/SetNext',
        request_serializer=guruguru__pb2.SetNextRequest.SerializeToString,
        response_deserializer=guruguru__pb2.SetNextResponse.FromString,
        )


class MemberServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Poke(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetNext(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MemberServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Poke': grpc.unary_unary_rpc_method_handler(
          servicer.Poke,
          request_deserializer=guruguru__pb2.PokeRequest.FromString,
          response_serializer=guruguru__pb2.PokeResponse.SerializeToString,
      ),
      'SetNext': grpc.unary_unary_rpc_method_handler(
          servicer.SetNext,
          request_deserializer=guruguru__pb2.SetNextRequest.FromString,
          response_serializer=guruguru__pb2.SetNextResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MemberService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
